### PR TITLE
Corrected image dims from `HWCN` to `WHCN` which solves #235

### PR DESCRIPTION
**Pull request by aditkumar72**
Changed dims in `permutedims` from `HWCN` to `WHCN`.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
This commit history is borked, but thanks for the contribution! We can merge the fix to permutedims pending fixing the commit history.

**Comment by aditkumar72** [comment]
Thanks @DhairyaLGandhi  for reviewing. Sorry for all those activities. I was bit confused. Do I need to fix something?

**Comment by ToucheSir** [comment]
The `dims` branch on your fork has a bunch of unrelated commits from #218. @DhairyaLGandhi was asking if you could just include https://github.com/FluxML/model-zoo/pull/306/commits/27bf1a6136b613621fd67ab5c05b1eb2525c2a2e (the actual change) so we can merge it.

**Comment by aditkumar72** [comment]
Thanks @ToucheSir for clearing out. Can you please give me some instruction's how to include only the actual change.
P.S. - I did my research but I didn't understood how to do it.

**Comment by ToucheSir** [comment]
The easiest way would be to create a new branch and cherry-pick the commit. Alternatively, you could rewind this branch back in line with master and cherry-pick.

**Comment by CarloLucibello** [comment]
or (this going to be very bad advice)  copy the folders you modified out of the repo, then checkout master, sync with origin, delete this branch, checkout the new branch, copy back the folders, force push on origin, checkout the diff for unwanted changes

**Comment by ToucheSir** [comment]
AFAICT the change is a [one-liner](https://github.com/FluxML/model-zoo/commit/27bf1a6136b613621fd67ab5c05b1eb2525c2a2e#diff-efa7aa54fdac02505ca61a1e86f5fdd1ccd7d929824dc180f40c99b08fd3d79eR307), so it may be even easier to PR it through the web interface :P

**Comment by aditkumar72** [comment]
Sorry again this time trying through the web interface.

**Comment by ToucheSir** [comment]
Oh no, you can't add commits to this PR that way. That keeps around the previous commits. You'd either have to start a new PR or clean out all of the commits on this one beforehand and force push. The thing to look for is the commits tab up top showing `(1)`, and that one commit being your `corrected dims of the images (HWCN -> WHCN)` change.

**Pull request closed without merging**
