### PR TITLE
Update models for maxpool

### PR DESCRIPTION
**Pull request by hossein-pourbozorg**
I just replaced every
```julia
x -> maxpool(x, (N,N))
```
with
```julia
MaxPool((N, N))
```

Before I do this changes, I got
```julia
ERROR: LoadError: MethodError: no method matching maxpool(::TrackedArray{…,Array{Float32,4}}, ::Tuple{Int64,Int64})
```
when I attempted to run
```julia
vision/mnist/conv.jl
vision/cifar10/cifar10.jl
```
examples. And after that, the error disappeared.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Note that these scripts come with Julia project files that specify a set of packages. Updating the syntax for newer packages is good, but the projects need to be updated as well.

**Comment by hossein-pourbozorg** [comment]
I used
```julia
] activate .
] update
```
on tutorials and vision projects.
I think, it is enough and I can update other projects in a new PR.

**Comment by cossio** [comment]
fixes https://github.com/FluxML/model-zoo/issues/153

**Comment by ketch** [comment]
I just hit this problem too and ended up here after a few minutes of searching.  It would be really helpful to have this merged; finding that the model-zoo examples don't run is quite discouraging for potential new users (like myself).

**Comment by cossio** [comment]
What's holding this merge? The conflicts are only on the Manifest, so that should not be an issue, right?

**Comment by hossein-pourbozorg** [comment]
Now that the #143 has been merged, and it updated the manifests. Should I revert the manifest update to resolve the conflicts?

**Comment by dhairyagandhi96** [comment]
Good to update the manifests. Good to do a look over and see all instances of maxpool are caught too

**Comment by hossein-pourbozorg** [comment]
@dhairyagandhi96 I pulled from master, updated manifests again and checked models by running them. All models ran without errors by the actual julia docker in a gitpod machine.
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_VERSION = 1.2.0
  JULIA_PATH = /usr/local/julia
```

I found out, in tutorials, `Project.toml` hasn't `Images` and `Statistics` but they used in the source code file, so I added them, and we should ignore generated `png` files by `vae.jl` in mnist directory. Also I removed `using CuArrays` because of `Flux` doesn't need it anymore for gpu supporting.

**Pull request closed without merging**
