### PR TITLE
Use the more idiomatic MaxPool((2,2))

### PR DESCRIPTION
**Pull request by fps**
instead of x -> maxpool(x, (2,2)). Looks a bit cleaner, too..

### CODE REVIEW

**Comment by fps** [comment]
I should add that actually I had to make this change and the one in https://github.com/FluxML/model-zoo/pull/145 to make the mnist convolutional example from the model zoo work at all. If I just use the conv.jl as is i get:

<pre>
fps@mango 09:42:07 ~/.../projects/cnn (master) $ julia conv2.jl 
[ Info: Loading data set
[ Info: Constructing model...
ERROR: LoadError: MethodError: no method matching maxpool(::TrackedArray{…,Array{Float32,4}}, ::Tuple{Int64,Int64})
Closest candidates are:
  maxpool(::TrackedArray, !Matched::PoolDims; kw...) at /home/fps/.julia/packages/Tracker/RRYy6/src/lib/array.jl:446
  maxpool(::AbstractArray{xT,N}, !Matched::PoolDims; kwargs...) where {xT, N} at /home/fps/.julia/packages/TimerOutputs/7zSea/src/TimerOutput.jl:198
Stacktrace:
 [1] (::getfield(Main, Symbol("##5#9")))(::TrackedArray{…,Array{Float32,4}}) at /home/fps/syncthing-uni/src/projects/cnn/conv2.jl:44
 [2] applychain(::Tuple{getfield(Main, Symbol("##5#9")),Conv{2,2,typeof(relu),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}},getfield(Main, Symbol("##6#10")),Conv{2,2,typeof(relu),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}},getfield(Main, Symbol("##7#11")),getfield(Main, Symbol("##8#12")),Dense{typeof(identity),TrackedArray{…,Array{Float32,2}},TrackedArray{…,Array{Float32,1}}},typeof(softmax)}, ::TrackedArray{…,Array{Float32,4}}) at /home/fps/.julia/packages/Flux/HfWCY/src/layers/basic.jl:31 (repeats 2 times)
 [3] (::Chain{Tuple{Conv{2,2,typeof(relu),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}},getfield(Main, Symbol("##5#9")),Conv{2,2,typeof(relu),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}},getfield(Main, Symbol("##6#10")),Conv{2,2,typeof(relu),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}},getfield(Main, Symbol("##7#11")),getfield(Main, Symbol("##8#12")),Dense{typeof(identity),TrackedArray{…,Array{Float32,2}},TrackedArray{…,Array{Float32,1}}},typeof(softmax)}})(::Array{Float32,4}) at /home/fps/.julia/packages/Flux/HfWCY/src/layers/basic.jl:33
 [4] top-level scope at none:0
 [5] include at ./boot.jl:326 [inlined]
 [6] include_relative(::Module, ::String) at ./loading.jl:1038
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at ./client.jl:267
 [9] _start() at ./client.jl:436
in expression starting at /home/fps/syncthing-uni/src/projects/cnn/conv2.jl:69
</pre>

If I do the change to MaxPool((2,2)) I get this:

<pre>
fps@mango 09:51:15 ~/.../projects/cnn (master) $ julia conv2.jl 
[ Info: Loading data set
[ Info: Constructing model...
[ Info: Beginning training loop...
ERROR: LoadError: MethodError: no method matching ∇maxpool(::Array{Float32,4}, ::Array{Float64,4}, ::Array{Float64,4}, ::PoolDims{2,(2, 2),(2, 2),(0, 0, 0, 0),(1, 1)})
Closest candidates are:
  ∇maxpool(::AbstractArray{T,N}, !Matched::AbstractArray{T,N}, !Matched::AbstractArray{T,N}, ::PoolDims; kwargs...) where {T, N} at /home/fps/.julia/packages/TimerOutputs/7zSea/src/TimerOutput.jl:198
Stacktrace:
 [1] (::getfield(Tracker, Symbol("##535#536")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},TrackedArray{…,Array{Float64,4}},PoolDims{2,(2, 2),(2, 2),(0, 0, 0, 0),(1, 1)},Array{Float64,4}})(::Array{Float32,4}) at /home/fps/.julia/packages/Tracker/RRYy6/src/lib/array.jl:450
 [2] back_(::Tracker.Call{getfield(Tracker, Symbol("##535#536")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},TrackedArray{…,Array{Float64,4}},PoolDims{2,(2, 2),(2, 2),(0, 0, 0, 0),(1, 1)},Array{Float64,4}},Tuple{Tracker.Tracked{Array{Float64,4}},Nothing}}, ::Array{Float32,4}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:35
 [3] back(::Tracker.Tracked{Array{Float64,4}}, ::Array{Float32,4}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:58
 [4] #13 at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38 [inlined]
 [5] foreach at ./abstractarray.jl:1867 [inlined]
 [6] back_(::Tracker.Call{getfield(Tracker, Symbol("##460#461")){TrackedArray{…,Array{Float64,4}}},Tuple{Tracker.Tracked{Array{Float64,4}},Nothing}}, ::Array{Float32,2}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38
 [7] back(::Tracker.Tracked{Array{Float64,2}}, ::Array{Float32,2}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:58
 [8] (::getfield(Tracker, Symbol("##13#14")){Bool})(::Tracker.Tracked{Array{Float64,2}}, ::Array{Float32,2}) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38
 [9] foreach(::Function, ::Tuple{Tracker.Tracked{Array{Float64,2}}}, ::Tuple{Array{Float32,2}}) at ./abstractarray.jl:1867
 [10] back_(::Tracker.Call{getfield(Tracker, Symbol("#back#548")){1,DataType,Tuple{TrackedArray{…,Array{Float64,2}}}},Tuple{Tracker.Tracked{Array{Float64,2}}}}, ::Array{Float32,2}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38
 ... (the last 8 lines are repeated 2 more times)
 [27] back(::Tracker.Tracked{Array{Float32,2}}, ::Array{Float32,2}, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:58
 [28] #13 at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38 [inlined]
 [29] foreach at ./abstractarray.jl:1867 [inlined]
 [30] back_(::Tracker.Call{getfield(Tracker, Symbol("##482#483")){TrackedArray{…,Array{Float32,2}}},Tuple{Tracker.Tracked{Array{Float32,2}}}}, ::Float32, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:38
 ... (the last 4 lines are repeated 2 more times)
 [39] back(::Tracker.Tracked{Float32}, ::Int64, ::Bool) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:58
 [40] #back!#15 at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:77 [inlined]
 [41] #back! at ./none:0 [inlined]
 [42] #back!#32 at /home/fps/.julia/packages/Tracker/RRYy6/src/lib/real.jl:16 [inlined]
 [43] back!(::Tracker.TrackedReal{Float32}) at /home/fps/.julia/packages/Tracker/RRYy6/src/lib/real.jl:14
 [44] gradient_(::getfield(Flux.Optimise, Symbol("##15#21")){typeof(loss),Tuple{Array{Float32,4},Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}}}, ::Tracker.Params) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:4
 [45] #gradient#24(::Bool, ::Function, ::Function, ::Tracker.Params) at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:164
 [46] gradient at /home/fps/.julia/packages/Tracker/RRYy6/src/back.jl:164 [inlined]
 [47] macro expansion at /home/fps/.julia/packages/Flux/HfWCY/src/optimise/train.jl:71 [inlined]
 [48] macro expansion at /home/fps/.julia/packages/Juno/TfNYn/src/progress.jl:133 [inlined]
 [49] #train!#12(::getfield(Flux.Optimise, Symbol("##16#22")), ::Function, ::Function, ::Tracker.Params, ::Array{Tuple{Array{Float32,4},Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}},1}, ::ADAM) at /home/fps/.julia/packages/Flux/HfWCY/src/optimise/train.jl:69
 [50] train!(::Function, ::Tracker.Params, ::Array{Tuple{Array{Float32,4},Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}},1}, ::ADAM) at /home/fps/.julia/packages/Flux/HfWCY/src/optimise/train.jl:67
 [51] top-level scope at /home/fps/syncthing-uni/src/projects/cnn/conv2.jl:93 [inlined]
 [52] top-level scope at ./none:0
 [53] include at ./boot.jl:326 [inlined]
 [54] include_relative(::Module, ::String) at ./loading.jl:1038
 [55] include(::Module, ::String) at ./sysimg.jl:29
 [56] exec_options(::Base.JLOptions) at ./client.jl:267
in expression starting at /home/fps/syncthing-uni/src/projects/cnn/conv2.jl:90
</pre>

If I then change the type of the 0.1 Float constant to Float32 it finally runs..

<pre>
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [fbb218c0] BSON v0.2.3
  [3da002f7] ColorTypes v0.8.0
  [3a865a2d] CuArrays v1.0.2
  [f0ed6883] FFmpegPipe v1.0.2
  [5789e2e9] FileIO v1.0.6
  [53c48c17] FixedPointNumbers v0.5.3
  [587475ba] Flux v0.8.3 #master (https://github.com/FluxML/Flux.jl.git)
  [86fae568] ImageView v0.9.0
  [916415d5] Images v0.17.3
  [ee78f7c6] Makie v0.9.4
  [b8a86587] NearestNeighbors v0.4.3
  [9b87118b] PackageCompiler v0.6.3
  [91a5bcdd] Plots v0.25.1
  [d6d074c3] VideoIO v0.6.5
</pre>

Maybe I'm confusing things though and both these PRs are misguided. Enlighten me :)

**Comment by shreyas-kowshik** [comment]
Runs perfectly on my system. Probably the issue might be relating to the versions of the packages.
Try this :
Go to the directory where `conv.jl` is present and run :  
```
julia --project=./Project.toml conv.jl
```

This will install all the dependencies associated with the example according to the versions it requires.
As for the changes, they seem fine to me, provided FluxML/NNlib.jl#121 gets merged in.

**Comment by fps** [comment]
Oh, right. My bad :)

**Comment by kraftpunk97** [comment]
@fps with FluxML/NNlib.jl#121 finally merged, this PR should be ready for merge as well.

**Comment by dhairyagandhi96** [comment]
LGTM

**Comment by hossein-pourbozorg** [comment]
The changes exist in #150, so should we close this PR?

**Pull request closed without merging**
