### PR TITLE
Transfer Learning Tutorial

### PR DESCRIPTION
**Pull request by dhairyagandhi96**
this is a first draft of a simple transfer learning demo.

Comments welcome

cc @MikeInnes, @ViralBShah

### CODE REVIEW

**Comment by AdarshKumar712** [comment]
@dhairyagandhi96 how about having an accompanied README.md file, where the main content of the tutorial may be discussed in a better way, like what's it about and so on?

**Comment by ViralBShah** [comment]
> @dhairyagandhi96 how about having an accompanied README.md file, where the main content of the tutorial may be discussed in a better way, like what's it about and so on?

@AdarshKumar712 That's a good idea. Make a PR?

**Comment by AdarshKumar712** [comment]
Sure! I will make one pretty soon.

**Comment by dhairyagandhi96** [comment]
Thanks all!

**Pull request merged**
