### PR TITLE
Corrected image dims from HWCN to WHCN

### PR DESCRIPTION
**Pull request by aditkumar72**
Changed dims in `permutedims` from `HWCN` to `WHCN`.

### CODE REVIEW

**Comment by aditkumar72** [comment]
@ToucheSir can you please review.

**Review by ToucheSir — APPROVED** [review]
Thanks!

**Comment by aditkumar72** [comment]
Thanks @ToucheSir for approving. A general question :- where can I get to know about high priority issues and important discussions related to model-zoo?

**Review by darsnack — APPROVED** [review]
Whoops, thanks @aditkumar72!

**Pull request merged**
