### PR TITLE
Reset state and add epochs in Char RNN example

### PR DESCRIPTION
**Pull request by mcognetta**
In the char-rnn example, the LSTM states were not reset between minibatches or epochs (but only one epoch was used, so this wasn't a real problem).

This PR redefines the loss to properly reset the model between minibatches. It also adds epochs (defaulted to 2 for now, not sure what others think should be the value. maybe 20?) to the training args.

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]
Thanks!

**Comment by ToucheSir** [comment]
Just one more thing before I merge this: can you confirm the sampling still works as before? RNN input handling can be finicky, and I want to make sure `train!` isn't slicing the input in unexpected ways.

**Comment by mcognetta** [comment]
Sure, here is a sample after 2 epochs.

```
Those as let your lord sweet brother are repented gree be suppent,
She knowledness as harched hearts become?

Page:
Ay, when it a worse; oredity it
bears togernable train,
Shall call you, and he stolen, it shall should pies a children: and yet thou mean.
By his last to will you well, though'd win almote: do this.

VALE:
Should have win, nor the wife the earth.

DON ADRIANO DE TESUS:
Good niceasolain, Herrehine! Shall York hath me,
Against bluntuded corse lately repore, Ajax in this sure.
You bids well.

CLAUPHIS:
You must be wounds as you shall so much heard
That will yet play thee, my bold, sir, my infinite, for the world give us and to my alleser,
My kept to foul this sister sign boys: should give him hands:
the mastering he is a-conslagied in, she done.

DON ADRIANO DE ARRANTI:
It is exlelves me a right of those jour ready come:
If you go as I she was
not I lend us Rousines think to Milan?

Old Sainn:
God never your English carding as
bowny, or impewing bedden will b
```

**Comment by ToucheSir** [comment]
Wonderful :)

**Comment by bhvieira** [comment]
FYI, if you reset within the loss, then the initial state will be optimized as well. That can be undesirable (probably not in this example though)

**Pull request merged**
