### PR TITLE
Updated DQN CartPole example to utilise Gym's Space types

### PR DESCRIPTION
**Pull request by kraftpunk97**
The DQN example which uses the CartPole environment has been updated to stop converting the actions (`Discrete(2)`) to `{-1, 1}`. Please refer to this [PR](https://github.com/FluxML/Gym.jl/pull/29) for more details.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Bump @tejank10

**Comment by kraftpunk97** [comment]
@tejank10 commenting here because this is seems like a more relevant thread for the issue. So as mentioned in the other PR, the DiffRL model trains, but gives a really ugly Internal error which has been recorded in [this gist](https://gist.github.com/kraftpunk97/0f65971784b631cf509bae54faf4f512). The script runs "fine", but if possible, I would like to avoid... this.

**Comment by tejank10** [comment]
Also updated the DQN example to use zygote

**Comment by MikeInnes** [comment]
@tejank10 feel free to merge if you're happy with it (or lmk if you need commit).

**Comment by tejank10** [comment]
Thanks, @kraftpunk97!

**Pull request merged**
