### PR TITLE
Add gitpod config

### PR DESCRIPTION
**Pull request by hossein-pourbozorg**
I just add a simple [gitpod](https://www.gitpod.io/) config.
When someone open this repository by gitpod, it should install julia language first and optionally julia extension, so I just add julia docker image and julia vscode extension to the repository's gitpod config and now everyone can develop or run models in gitpod for free. :smile:

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
@hossein-pourbozorg this seems interesting indeed, but I am not familiar with it (and I guess many would share that thought).

Would it be possible to add a note to the README about its purpose, and the link to access it. Also mention that it isn't an officially maintained feature and is subject to all the caveats that that comes with?

**Comment by hossein-pourbozorg** [comment]
You can check changes [before](https://github.com/FluxML/model-zoo) and [after](https://gitpod.io/#https://github.com/hossein-pourbozorg/model-zoo/tree/add_gitpod) the config.

**Comment by hossein-pourbozorg** [comment]
With [its extension](https://chrome.google.com/webstore/detail/gitpod-online-ide/dodmmooeoklaejobgleioelladacbeki), everyone can use it. so we can have it without any guide on how to open the repository.
unnamed

**Comment by dhairyagandhi96** [comment]
Sweet, thanks so much, @hossein-pourbozorg !

**Pull request merged**
