### PR TITLE
Missing commit to fix cifar10 example

### PR DESCRIPTION
**Pull request by joostveenema**
I apparently forget to commit these lines. If not included the script complains about the missing device function This is not the nicest solution but it does at least fix the script.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
what do you mean it is not the nicest solution? you have in mind a different code pattern to send models to cpu/gpu?

**Comment by joostveenema** [comment]
It now has the following lines in both the train and test function:

```
    if CUDA.has_cuda()
         device = gpu
     else
         device = cpu
     end
```

I think there should only be one check for a GPU. But this is probably something to keep in mind when rewriting the model in a tutorial/notebook style and just leave it like this for now.

**Comment by CarloLucibello** [comment]
`device = CUDA.has_cuda() ? gpu : cpu` in the global space and pass it to test and train?

**Comment by DhairyaLGandhi** [comment]
I agree it's ugly and adds nothing. `gpu` is a no-op when there isn't a working GPU available, so you don't have to have it here at all.

**Comment by joostveenema** [comment]
Just using `gpu` and removing the device handling seems like to the way to go here. Updated the PR.

**Comment by CarloLucibello** [comment]
i find it better to be explicit, but it's not important

**Pull request merged**
