### PR TITLE
Update char-rnn.jl

### PR DESCRIPTION
**Pull request by rajraomichigan**
should be stop = onehot("_", alphabet)
and not stop = onehot('_  ', alphabet)
double quotes as opposed to single quotes

### CODE REVIEW

**Comment by rajraomichigan** [comment]
should be double quotes instead of single quotes

**Comment by MikeInnes** [comment]
Why?

**Comment by rajraomichigan** [comment]
It didn’t work the way it is listed :)
________________________________

**Comment by MikeInnes** [comment]
Can you clarify "doesn't work"? Are you getting some error?

It's working for me, and notice that the alphabet is defined as `alphabet = [unique(text)..., '_']`, so `" "` will not be found in the alphabet correctly.

**Comment by rajraomichigan** [comment]
I was getting an error when I tried it (while Alan was in SG)..must have been a copy/paste bug ...all set! Thanks!


________________________________

**Pull request closed without merging**
